esphome:
  name: haier-ac-kfr26gw-ircontroller

web_server:
  port: 80
  version: 3

esp8266:
  board: esp_wroom_02
  restore_from_flash: true

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: WPhA2uqKZKOSxxxrkG72mmQRLRV5naqvJrTI2dfRzU4=

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "IRController Fallback Hotspot"
    password: WYoNyu2tR5qucL

captive_portal:

external_components:
  - source: github://CCBP/ESPHome-HaierAC_KFR26GW-IRController@main
    components: [ haier_ac_kfr26gw ]

haier_ac_kfr26gw:
  id: haier_ac
  name: "Haier Air Conditioner"
  pin: GPIO4
